export const CHOOSE_PAYMENT_REQUESTED = 'CHOOSE_PAYMENT_REQUESTED';
export const CHOOSE_PAYMENT_SUCCESSED = 'CHOOSE_PAYMENT_SUCCESSED';
export const GET_DETAIL_PENDING_PRODUCT_SUCCESSED = 'GET_DETAIL_PENDING_PRODUCT_SUCCESSED';
