# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: reflaunt/circle-ci-nodejs:v0.1

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-rf-webapp-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-rf-webapp-

      - run: yarn install

      - run:
         name: Deploying
         command: |
           touch ./src/environments/environment.ts
           if [[ "$CIRCLE_BRANCH" == "dev" ]]; then
             yarn build_dev
           fi
           if [[ "$CIRCLE_BRANCH" == "production" ]]; then
             yarn build_prod
           fi

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-rf-webapp-{{ checksum "package.json" }}

      - run:
          name: Deploying
          command: |
            if [[ "$CIRCLE_BRANCH" == "dev" ]]; then
              aws s3 cp --region=ap-southeast-1 --recursive dist s3://my-dev.reflaunt.com
            fi

            if [[ "$CIRCLE_BRANCH" == "production" ]]; then
              aws s3 cp --region=ap-southeast-1 --recursive dist s3://my.reflaunt.com
            fi
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
                - production
