export const FETCH_USER_WALLET_REQUESTED = 'FETCH_USER_WALLET_REQUESTED';
export const FETCH_USER_WALLET_SUCCESSED = 'FETCH_USER_WALLET_SUCCESSED';
export const FETCH_USER_WALLET_ERRORS = 'FETCH_USER_WALLET_ERRORS';

export const FETCH_PENDING_PRODUCTS_SUCCESSED = 'FETCH_PENDING_PRODUCTS_SUCCESSED';


