export const RENDER_FILL_BANK_ACCOUNT_FORM_REQUESTED =
  'RENDER_FILL_BANK_ACCOUNT_FORM_REQUESTED';
export const UPDATE_INPUTS_ACCOUNT_PAYMENT_FORM_REQUESTED =
  'UPDATE_INPUTS_ACCOUNT_PAYMENT_FORM_REQUESTED';
export const UPDATE_INPUTS_VALUES_PAYMENT_FORM_REQUESTED =
  'UPDATE_INPUTS_VALUES_PAYMENT_FORM_REQUESTED';

export const SAVE_BANK_ACCOUNT_DETAIL_REQUESTED =
  'SAVE_BANK_ACCOUNT_DETAIL_REQUESTED';
export const SAVE_BANK_ACCOUNT_DETAIL_SUCCESSED =
  'SAVE_BANK_ACCOUNT_DETAIL_SUCCESSED';

export const UPDATE_PAYMENT_ACCOUNT_FROM_REQUESTED =
  'UPDATE_PAYMENT_ACCOUNT_FROM_REQUESTED';

export const UPDATE_BANK_ACCOUNT_DETAIL_REQUESTED =
  'UPDATE_BANK_ACCOUNT_DETAIL_REQUESTED';
export const UPDATE_BANK_ACCOUNT_DETAIL_SUCCESSED =
  'UPDATE_BANK_ACCOUNT_DETAIL_SUCCESSED';

export const RENDER_FILL_CONFIRM_ADDRESS_FORM_REQUESTED =
  'RENDER_FILL_CONFIRM_ADDRESS_FORM_REQUESTED';
export const UPDATE_INPUTS_ADDRESS_LANDING_PAGE_REQUESTED =
  'UPDATE_INPUTS_ADDRESS_LANDING_PAGE_REQUESTED';
export const UPDATE_ALPHA_2_CODE_VALUE_ADDRESS_LANDINGPAGE_REQUESTED =
  'UPDATE_ALPHA_2_CODE_VALUE_ADDRESS_LANDINGPAGE_REQUESTED';
export const UPDATE_SELLER_CONFIRM_ADDRESS_FROM_REQUESTED =
  'UPDATE_SELLER_CONFIRM_ADDRESS_FROM_REQUESTED';
export const SAVE_SELLER_CONFIRM_ADDRESS_DETAIL_REQUESTED =
  'SAVE_SELLER_CONFIRM_ADDRESS_DETAIL_REQUESTED';
export const SAVE_SELLER_CONFIRM_ADDRESS_DETAIL_SUCCESSED =
  'SAVE_SELLER_CONFIRM_ADDRESS_DETAIL_SUCCESSED';
export const GET_DEFAULT_ADDRESS_REQUESTED = 'GET_DEFAULT_ADDRESS_REQUESTED';
