export const GET_ALL_PRODUCT_REQUESTED = 'GET_ALL_PRODUCT_REQUESTED';
export const GET_ALL_PRODUCT_SUCCESSED = 'GET_ALL_PRODUCT_SUCCESSED';
export const FETCH_PRODUCT_REQUESTED = 'FETCH_PRODUCT_REQUESTED';
export const FETCH_PRODUCT_SUCCESSED = 'FETCH_PRODUCT_SUCCESSED';
