export const FETCH_MESSAGES_REQUESTED = 'FETCH_MESSAGES_REQUESTED';
export const FETCH_MESSAGES_SUCCESSED = 'FETCH_MESSAGES_SUCCESSED';

export const SELECTED_MESSAGES_REQUESTED = 'SELECTED_MESSAGES_REQUESTED';

export const POST_MESSAGE_REQUESTED = 'POST_MESSAGE_REQUESTED';
export const POST_MESSAGE_SUCCESSED = 'POST_MESSAGE_SUCCESSED';

