export const GET_ALL_VOUCHERS_REQUESTED = 'GET_ALL_VOUCHERS_REQUESTED';
export const GET_ALL_VOUCHERS_SUCCESSED = 'GET_ALL_VOUCHERS_SUCCESSED';


export const REDEEM_VOUCHER_REQUESTED = 'REDEEM_VOUCHER_REQUESTED';
export const REDEEM_VOUCHER_SUCCESSED = 'REDEEM_VOUCHER_SUCCESSED';
