export const FETCH_USER_WALLET_VOUCHERS_COM_SUCCESSED = 'FETCH_USER_WALLET_VOUCHERS_COM_SUCCESSED';
export const CHOOSE_BRANCH_REQUESTED = 'CHOOSE_BRANCH_REQUESTED';

export const GET_VOUCHERS_REQUESTED = 'GET_VOUCHERS_REQUESTED';
export const GET_VOUCHERS_SUCCESSED = 'GET_VOUCHERS_SUCCESSED';
