export const FETCH_PRODUCT_DETAIL_REQUESTED = 'FETCH_PRODUCT_DETAIL_REQUESTED';
export const FETCH_PRODUCT_DETAIL_SUCCESSED = 'FETCH_PRODUCT_DETAIL_SUCCESSED';
export const PRODUCT_DETAIL_COMPONENT = 'PRODUCT_DETAIL_COMPONENT';


